# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('numero', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('indirizzo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funzionari',
            fields=[
                ('codfisc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('codimm', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('indirizzo', models.CharField(max_length=100)),
                ('comune', models.CharField(max_length=30)),
                ('numaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Materiali',
            fields=[
                ('sigla', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, null=True)),
                ('potcancerogeno', models.BooleanField()),
                ('cancerogeno', models.BooleanField()),
                ('fuorilegge', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pratica',
            fields=[
                ('codprat', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apertprat', models.DateField()),
                ('primsoll', models.DateField()),
                ('rispprimsoll', models.DateField(null=True)),
                ('secsoll', models.DateField(null=True)),
                ('inizlavori', models.DateField()),
                ('finlavori', models.DateField()),
                ('collaudo', models.DateField()),
                ('esitcoll', models.CharField(max_length=20)),
                ('chiusuraprat', models.DateField(null=True)),
                ('codfunz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Funzionari')),
                ('codimm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Immobile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedaimmobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codimm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Funzionari')),
                ('codmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Immobile')),
            ],
        ),
    ]
